#!/bin/bash
# chkconfig: 2345 90 90 
# description: cdh.service ....

agent=/opt/cm-5.*/etc/init.d/cloudera-scm-agent
cmd=$1

case $1 in 
  start)        $agent start ;;
  stop)         $agent stop  ;;
  status)       $agent status ;;
  restart)      $agent restart;;
  * )           echo "Usage :   $agent start|restart|stop|status"
esac
